# Generated by Django 5.1.5 on 2025-02-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_Product_Mng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
