# Generated by Django 5.1.4 on 2024-12-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('warranty_period', models.IntegerField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
